#!/bin/sh

for k in 50 60 70 80 90 100  
do

mkdir ecut$k
cp jobqe.sh ecut$k/ 
cd ecut$k
kr=$(echo "$k * 4.0" | bc -l )

sed "s/ECUT/${k}/g" ../scf.READ > tempqe
sed "s/RHOCUT/${kr}/g" tempqe > scf.input
rm tempqe
sbatch jobqe.sh 

cd .. 

done
