#!/bin/sh

for k in 40 50 60 70 80 90 100 110 120 130 140 150  
do

mkdir ecut$k
cp submit.job ecut$k/ 
cd ecut$k
kr=$(echo "$k * 6.0" | bc -l )

sed "s/ECUT/${k}/g" ../scf.READ > tempqe
sed "s/RHOCUT/${kr}/g" tempqe > scf.in
rm tempqe
sbatch submit.job 

cd .. 

done
