#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
##SBATCH --mem=180000
#SBATCH --time=11:59:59
#SBATCH --account=Sis20_baroni
#SBATCH --partition=skl_usr_prod
#SBATCH --job-name=USPEX-2
##SBATCH --mail-user=afiorent@sissa.it
#SBATCH --mail-type=ALL

#umask -S u=rwx,g=r,o=r
module purge
module load profile/phys
module load autoload qe/6.3
env

mpirun -n 32 pw.x < qe.in > output
