#!/bin/sh

for k in 60 70 #5 10 20 40
do

mkdir kpoints$k
cp jobqe.sh kpoints$k/ 
cd kpoints$k

sed "s/KPOINTS/${k}/g" ../qe.READ > qe.input 
sed -i 's/ECUT/50/g' qe.input 

sbatch jobqe.sh 

cd .. 

done
